name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.2
  lottie: ^2.6.0  # For smooth animations
  soft_edge_blur: ^0.1.3
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^8.0.2
  json_annotation: ^4.8.1
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.9.0
  # cloud_firestore: ^4.9.1
  # firebase_storage: ^11.2.6
  path_provider: ^2.1.1
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  injectable: ^2.0.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  source_gen: ^1.4.0
  injectable_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/teeem-logo-in.mp4
    - assets/videos/teeem-logo-in.mp4.lottie.json
